version: "3.8"

services:
  web:
    build:
      context: ./my-webpage-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  api:
    build:
      context: ./my-webpage-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DB_URL: mongodb://db/uservisits
  db:
    image: mongo:4.0-xenial
    ports:
      - "27017:27017"
    volumes:
      - my-webpage:/data/db

volumes:
  my-webpage: